### ISSUE TITLE
Microsoft Defender Issue 

### ISSUE THREAD

**Issue by taremooo** [Bert-JanP/Hunting-Queries-Detection-Rules#43]
My organizations Microsoft Defender custom detection rules have all disappeared, about half of our blocked IOC's have vanished as well. I'd like to know if this is peculiar to anyone and if there is a solution? 

![Detection ](https://github.com/Bert-JanP/Hunting-Queries-Detection-Rules/assets/63564516/2b9bb541-d05c-4b36-94b4-e6fff0b51254)

**Comment by Bert-JanP** [comment]
Hi, I am not aware of this issue. If you have enabled UAL for MDE you can view what caused this activity. If there is no entry and the UAL activities are enabled I suggest creating a support ticket for MS Support to investigate this particular issue. Both Indicator and custom detection rule deletions/changes (and creations) are logged in UAL.
